excerpt_separator: ""
pygments: "pygments"
markdown: kramdown
url: http://aufschieben.github.io
title: Prokrastination.
tagline:  Psychoanalyse und gesellschaftlicher Kontext.
description: Ein Blog zum Forschungsprojekt "Prokrastination. Psychoanalyse und gesellschaftlicher Kontext."
paginate: 5
